version: '2'

services:
  app:  
    image: nextcloud
    ports:
      - 80:80
    links:
      - db
    volumes:
      - /data
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_DATA_DIR=/data
